export const categories = [
  { id: 'plumber', name: 'Plumber', icon: 'Wrench', helperCount: 124 },
  { id: 'electrician', name: 'Electrician', icon: 'Zap', helperCount: 98 },
  { id: 'carpenter', name: 'Carpenter', icon: 'Hammer', helperCount: 76 },
  { id: 'cleaner', name: 'Cleaner', icon: 'Sparkles', helperCount: 215 },
  { id: 'mechanic', name: 'Mechanic', icon: 'Car', helperCount: 87 },
  { id: 'ac-repair', name: 'AC Repair', icon: 'Wind', helperCount: 63 },
  { id: 'painter', name: 'Painter', icon: 'Paintbrush', helperCount: 54 },
  { id: 'gardener', name: 'Gardener', icon: 'Flower2', helperCount: 42 },
];

export const helpers = [
  {
    id: '1',
    name: 'Rahul Sharma',
    profession: 'Plumber',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    rating: 4.9,
    reviewCount: 127,
    distance: '0.8 km',
    priceRange: '₹400-600/hr',
    hourlyRate: 450,
    available: true,
    verified: true,
    bio: 'Licensed master plumber with 12 years of experience. Specializing in emergency repairs, pipe installations, and bathroom renovations.',
    skills: ['Pipe Repair', 'Water Heater', 'Drain Cleaning', 'Bathroom Installation'],
    completedJobs: 342,
    location: { lat: 28.6139, lng: 77.2090 },
  },
  {
    id: '2',
    name: 'Priya Patel',
    profession: 'Electrician',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    rating: 4.8,
    reviewCount: 89,
    distance: '1.2 km',
    priceRange: '₹500-800/hr',
    hourlyRate: 550,
    available: true,
    verified: true,
    bio: 'Certified electrician specializing in residential and commercial electrical work. Safety is my top priority.',
    skills: ['Wiring', 'Panel Upgrades', 'Lighting', 'Troubleshooting'],
    completedJobs: 256,
    location: { lat: 28.6159, lng: 77.2070 },
  },
  {
    id: '3',
    name: 'Amit Kumar',
    profession: 'Carpenter',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    rating: 4.7,
    reviewCount: 64,
    distance: '1.5 km',
    priceRange: '₹350-550/hr',
    hourlyRate: 400,
    available: false,
    verified: true,
    bio: 'Skilled carpenter with expertise in custom furniture, cabinetry, and home renovations.',
    skills: ['Custom Furniture', 'Cabinetry', 'Deck Building', 'Repairs'],
    completedJobs: 189,
    location: { lat: 28.6119, lng: 77.2110 },
  },
  {
    id: '4',
    name: 'Sneha Gupta',
    profession: 'Cleaner',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    rating: 5.0,
    reviewCount: 203,
    distance: '0.5 km',
    priceRange: '₹250-400/hr',
    hourlyRate: 300,
    available: true,
    verified: true,
    bio: 'Professional cleaner providing deep cleaning, move-in/out cleaning, and regular maintenance services.',
    skills: ['Deep Cleaning', 'Move-in/out', 'Office Cleaning', 'Sanitization'],
    completedJobs: 512,
    location: { lat: 28.6149, lng: 77.2080 },
  },
  {
    id: '5',
    name: 'Vikram Singh',
    profession: 'Mechanic',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    rating: 4.6,
    reviewCount: 78,
    distance: '2.1 km',
    priceRange: '₹450-700/hr',
    hourlyRate: 500,
    available: true,
    verified: false,
    bio: 'ASE certified mechanic offering on-site repairs and maintenance for all vehicle makes and models.',
    skills: ['Engine Repair', 'Brake Service', 'Oil Change', 'Diagnostics'],
    completedJobs: 167,
    location: { lat: 28.6169, lng: 77.2050 },
  },
  {
    id: '6',
    name: 'Anjali Desai',
    profession: 'AC Repair',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
    rating: 4.9,
    reviewCount: 112,
    distance: '1.8 km',
    priceRange: '₹550-850/hr',
    hourlyRate: 600,
    available: true,
    verified: true,
    bio: 'HVAC specialist with expertise in AC installation, repair, and maintenance for residential and commercial units.',
    skills: ['AC Installation', 'Repair', 'Maintenance', 'Duct Cleaning'],
    completedJobs: 298,
    location: { lat: 28.6129, lng: 77.2060 },
  },
];

export const services = [
  { id: '1', name: 'Basic Inspection', description: 'Quick inspection and diagnosis', basePrice: 300, duration: '30 min' },
  { id: '2', name: 'Standard Repair', description: 'Common repairs and fixes', basePrice: 750, duration: '1-2 hrs' },
  { id: '3', name: 'Full Service', description: 'Complete service package', basePrice: 1500, duration: '2-4 hrs' },
  { id: '4', name: 'Emergency Service', description: '24/7 emergency assistance', basePrice: 1000, duration: 'ASAP' },
];

export const reviews = [
  {
    id: '1',
    userName: 'Aman D.',
    userImage: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=100&h=100&fit=crop&crop=face',
    rating: 5,
    comment: 'Excellent work! Fixed my leaky faucet in no time. Very professional and clean.',
    date: '2 days ago',
  },
  {
    id: '2',
    userName: 'Kavita S.',
    userImage: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face',
    rating: 5,
    comment: 'Super responsive and skilled. Highly recommend for any plumbing needs!',
    date: '1 week ago',
  },
  {
    id: '3',
    userName: 'Rajiv K.',
    userImage: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&h=100&fit=crop&crop=face',
    rating: 4,
    comment: 'Good service, arrived on time. Price was fair for the quality of work.',
    date: '2 weeks ago',
  },
];

export const testimonials = [
  {
    id: '1',
    name: 'Ritu Sharma',
    role: 'Homeowner',
    image: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=100&h=100&fit=crop&crop=face',
    content: 'DailyHire saved me during a plumbing emergency. Found a verified plumber within 15 minutes who fixed everything the same day!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Rohan Kapoor',
    role: 'Small Business Owner',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face',
    content: 'We use DailyHire for all our office maintenance needs. The quality of professionals and transparent pricing is unmatched.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Neha Verma',
    role: 'Property Manager',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    content: 'Managing 50+ units is a breeze with DailyHire. Quick booking, reliable helpers, and fair prices every time.',
    rating: 5,
  },
];
